version: "3.8"
services:
  api:
    image: node:16.5.0
    env_file:
      - ./app/.env.dev
    command: sh -c "npm install && npm start"
    volumes:
      - ./app/:/app/:rw
    working_dir: /app/

  nginx:
    restart: always
    image: nginx:1.21.1
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
